
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package smpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int PLUS = 3;
  public static final int RPAREN = 9;
  public static final int SEMI = 12;
  public static final int LPAREN = 8;
  public static final int LBRACKET = 10;
  public static final int COLON = 14;
  public static final int RBRACKET = 11;
  public static final int STRING = 18;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int INTEGER = 15;
  public static final int REAL = 16;
  public static final int VAR = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "COLON",
  "INTEGER",
  "REAL",
  "VAR",
  "STRING"
  };
}

